/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ejercicioPilas;

/**
 *
 * @author LENOVO
 */
public class PilaGrafico extends javax.swing.JDialog {

    /**
     * Creates new form PilaGrafico
     */
    public PilaGrafico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tope1.setVisible(false);
                tope2.setVisible(false);
                        tope3.setVisible(false);
                                tope4.setVisible(false);
                                        tope5.setVisible(false);
                                  
                                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campo1 = new javax.swing.JTextField();
        campo2 = new javax.swing.JTextField();
        campo3 = new javax.swing.JTextField();
        campo4 = new javax.swing.JTextField();
        campo5 = new javax.swing.JTextField();
        tope1 = new javax.swing.JLabel();
        tope2 = new javax.swing.JLabel();
        tope3 = new javax.swing.JLabel();
        tope4 = new javax.swing.JLabel();
        tope5 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        modTxf = new javax.swing.JTextField();
        tope0 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        campo1.setEditable(false);

        campo2.setEditable(false);

        campo3.setEditable(false);

        campo4.setEditable(false);

        campo5.setEditable(false);

        tope1.setText("Tope -->");

        tope2.setText("Tope -->");

        tope3.setText("Tope -->");

        tope4.setText("Tope -->");

        tope5.setText("Tope -->");

        btn1.setText("Push");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("Pop");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("Peek");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        modTxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modTxfActionPerformed(evt);
            }
        });

        tope0.setText("Tope -->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tope0)
                    .addComponent(tope1)
                    .addComponent(tope2)
                    .addComponent(tope3)
                    .addComponent(tope4)
                    .addComponent(tope5))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(modTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tope5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tope4)
                    .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn1)
                        .addComponent(btn2)
                        .addComponent(btn3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tope3))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tope2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(modTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tope1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tope0)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     MiStack miPila = new MiStack(5);
     int tope= miPila.tope;
     
     /**
      * este metodo permite interactuar con el tope
      * @param tope 
      */
     public  void mostrarTope(int tope){
      tope0.setVisible(false);   
         tope1.setVisible(false);
                tope2.setVisible(false);
                        tope3.setVisible(false);
                                tope4.setVisible(false);
                                        tope5.setVisible(false);
                                        
         switch (tope) {
             case -1:
                 tope0.setVisible(true);
                 break;
           case 0 : 
              
               tope1.setVisible(true);
               
               break;
           case 1 : 
              
               tope2.setVisible(true);
               
               break;
           case 2 : 
              
               tope3.setVisible(true);
           
               break;
           case 3 : 
               
               tope4.setVisible(true);
            
               break;
           case 4 : 
              
               tope5.setVisible(true);
               
               break;     
       }        
     }
    /**
 * Push mostrará el contenido del cuadro de texto en la siguiente posición 
 * que tenga la pila disponible y subir el indicador de la pila, en caso que la pila
 * @param evt 
 */
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
         
        if (tope<4){
             tope++;
        String valor=modTxf.getText();
        miPila.push(valor);
       switch (tope) {
           case 0 : 
               campo1.setText(miPila.peek());
              mostrarTope(tope);
               
               break;
           case 1 : 
               campo2.setText(miPila.peek());
               mostrarTope(tope);
            
               break;
           case 2 : 
               campo3.setText(miPila.peek());
               mostrarTope(tope);
              
               break;
           case 3 : 
               campo4.setText(miPila.peek());
               mostrarTope(tope);
               
               break;
           case 4 : 
               campo5.setText(miPila.peek());
               mostrarTope(tope);
               
               break;     
       } 
       
        } else {
             javax.swing.JOptionPane.showMessageDialog(
            null,
            "Ya no hay espacio en la pila, todos los campos están llenos.",
            "Pila llena",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        } 
        modTxf.setText("");
    }//GEN-LAST:event_btn1ActionPerformed
/**
 * este boton elimina el tope muestra el tope en el campo designado para agregar y baja el tope
 * @param evt 
 */
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        
        if (tope>=0){
            
            
            
           switch (tope) {
           case 0 : 
               modTxf.setText(miPila.peek());
               campo1.setText("");
              mostrarTope(tope-1);
               
               break;
           case 1 : 
               modTxf.setText(miPila.peek());
               campo2.setText("");
               mostrarTope(tope-1);
               
               break;
           case 2 : 
               modTxf.setText(miPila.peek());
               campo3.setText("");
               mostrarTope(tope-1);
              
               break;
           case 3 : 
             modTxf.setText(miPila.peek());
               campo4.setText("");
               mostrarTope(tope-1);
               
               break;
           case 4 : 
             modTxf.setText(miPila.peek());
               campo5.setText("");
               mostrarTope(tope-1);
               
               break;     
       }
           miPila.pop();
          tope--;
        }
        
    }//GEN-LAST:event_btn2ActionPerformed
/**
 * este boton solo muestra  lo que hay en el tope sin modificar nada 
 * @param evt 
 */
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        modTxf.setText(miPila.peek());
    }//GEN-LAST:event_btn3ActionPerformed

    private void modTxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modTxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modTxfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilaGrafico dialog = new PilaGrafico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JTextField campo1;
    private javax.swing.JTextField campo2;
    private javax.swing.JTextField campo3;
    private javax.swing.JTextField campo4;
    private javax.swing.JTextField campo5;
    private javax.swing.JTextField modTxf;
    private javax.swing.JLabel tope0;
    private javax.swing.JLabel tope1;
    private javax.swing.JLabel tope2;
    private javax.swing.JLabel tope3;
    private javax.swing.JLabel tope4;
    private javax.swing.JLabel tope5;
    // End of variables declaration//GEN-END:variables
}
